version: '3.8'

services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_COM_GENZ_TRANSLATOR=DEBUG
    volumes:
      - ./backend/src:/app/src
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    command: ["npm", "start"]

  database:
    environment:
      - POSTGRES_DB=genz_translator_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: